<?php 
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category    DH
 * @package     DH_Sociallogin
 * @copyright   Copyright (c) 2013 DHZoanku
 * @license     License GNU General Public License version 2 or later; 
 */
?>
<?php 
if (Mage::getStoreConfig('sociallogin/general/enable')){
?>
<div class="dh-social-button">
	<p><?php echo Mage::helper('sociallogin')->__('Or Login width:')?></p>
	<?php if (Mage::helper('sociallogin')->useFaceBook()){?>
	<button type="button" class="dh-button fb-button" onclick="setLocation('<?php echo $this->getUrl('sociallogin/account/fblogin');?>')"><?php echo Mage::helper('sociallogin')->__('Facebook') ?></button>
	<?php } ?>
	<?php if (Mage::helper('sociallogin')->useGoogle()){?>
	<button type="button" class="dh-button go-button" onclick="setLocation('<?php echo $this->getUrl('sociallogin/account/gologin');?>')"><?php echo Mage::helper('sociallogin')->__('Google') ?></button>
	<?php } ?>
	<?php if (Mage::helper('sociallogin')->useTwitter()){?>
	<button type="button" class="dh-button tw-button" onclick="setLocation('<?php echo $this->getUrl('sociallogin/account/twlogin');?>')"><?php echo Mage::helper('sociallogin')->__('Twitter') ?></button>
	<?php } ?>
	<?php if (Mage::helper('sociallogin')->useYahoo()){?>
	<button type="button" class="dh-button ya-button" onclick="setLocation('<?php echo $this->getUrl('sociallogin/account/yalogin');?>')"><?php echo Mage::helper('sociallogin')->__('Yahoo') ?></button>
	<?php } ?>
</div>
<?php }?>